require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NounPhrasesController do

  # This should return the minimal set of attributes required to create a valid
  # NounPhrase. As you add validations to NounPhrase, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "noun_phrase" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NounPhrasesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all noun_phrases as @noun_phrases" do
      noun_phrase = NounPhrase.create! valid_attributes
      get :index, {}, valid_session
      assigns(:noun_phrases).should eq([noun_phrase])
    end
  end

  describe "GET show" do
    it "assigns the requested noun_phrase as @noun_phrase" do
      noun_phrase = NounPhrase.create! valid_attributes
      get :show, {:id => noun_phrase.to_param}, valid_session
      assigns(:noun_phrase).should eq(noun_phrase)
    end
  end

  describe "GET new" do
    it "assigns a new noun_phrase as @noun_phrase" do
      get :new, {}, valid_session
      assigns(:noun_phrase).should be_a_new(NounPhrase)
    end
  end

  describe "GET edit" do
    it "assigns the requested noun_phrase as @noun_phrase" do
      noun_phrase = NounPhrase.create! valid_attributes
      get :edit, {:id => noun_phrase.to_param}, valid_session
      assigns(:noun_phrase).should eq(noun_phrase)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NounPhrase" do
        expect {
          post :create, {:noun_phrase => valid_attributes}, valid_session
        }.to change(NounPhrase, :count).by(1)
      end

      it "assigns a newly created noun_phrase as @noun_phrase" do
        post :create, {:noun_phrase => valid_attributes}, valid_session
        assigns(:noun_phrase).should be_a(NounPhrase)
        assigns(:noun_phrase).should be_persisted
      end

      it "redirects to the created noun_phrase" do
        post :create, {:noun_phrase => valid_attributes}, valid_session
        response.should redirect_to(NounPhrase.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved noun_phrase as @noun_phrase" do
        # Trigger the behavior that occurs when invalid params are submitted
        NounPhrase.any_instance.stub(:save).and_return(false)
        post :create, {:noun_phrase => { "noun_phrase" => "invalid value" }}, valid_session
        assigns(:noun_phrase).should be_a_new(NounPhrase)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NounPhrase.any_instance.stub(:save).and_return(false)
        post :create, {:noun_phrase => { "noun_phrase" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested noun_phrase" do
        noun_phrase = NounPhrase.create! valid_attributes
        # Assuming there are no other noun_phrases in the database, this
        # specifies that the NounPhrase created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NounPhrase.any_instance.should_receive(:update).with({ "noun_phrase" => "MyString" })
        put :update, {:id => noun_phrase.to_param, :noun_phrase => { "noun_phrase" => "MyString" }}, valid_session
      end

      it "assigns the requested noun_phrase as @noun_phrase" do
        noun_phrase = NounPhrase.create! valid_attributes
        put :update, {:id => noun_phrase.to_param, :noun_phrase => valid_attributes}, valid_session
        assigns(:noun_phrase).should eq(noun_phrase)
      end

      it "redirects to the noun_phrase" do
        noun_phrase = NounPhrase.create! valid_attributes
        put :update, {:id => noun_phrase.to_param, :noun_phrase => valid_attributes}, valid_session
        response.should redirect_to(noun_phrase)
      end
    end

    describe "with invalid params" do
      it "assigns the noun_phrase as @noun_phrase" do
        noun_phrase = NounPhrase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NounPhrase.any_instance.stub(:save).and_return(false)
        put :update, {:id => noun_phrase.to_param, :noun_phrase => { "noun_phrase" => "invalid value" }}, valid_session
        assigns(:noun_phrase).should eq(noun_phrase)
      end

      it "re-renders the 'edit' template" do
        noun_phrase = NounPhrase.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NounPhrase.any_instance.stub(:save).and_return(false)
        put :update, {:id => noun_phrase.to_param, :noun_phrase => { "noun_phrase" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested noun_phrase" do
      noun_phrase = NounPhrase.create! valid_attributes
      expect {
        delete :destroy, {:id => noun_phrase.to_param}, valid_session
      }.to change(NounPhrase, :count).by(-1)
    end

    it "redirects to the noun_phrases list" do
      noun_phrase = NounPhrase.create! valid_attributes
      delete :destroy, {:id => noun_phrase.to_param}, valid_session
      response.should redirect_to(noun_phrases_url)
    end
  end

end
